# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83db623c10a7c8bb28defff7455b89309ca541066960df43e0d32dec7f3f2fd755db51d4f691519157065a4fc0ce4c3dc37513a0f2615560e0b835de5e46320e

test:
  secret_key_base: c4d899469606381b16479784004941cac955fc2485580ebfc1028f873bd2418dd2dee4ec1b2a651c79b643fe2f8bef04ce198481c8033556bb5d56c844b114dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
